# This workflow will build a Java project with Maven and cache any dependencies.
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java Build

on: [push, pull_request]

jobs:
  build:
    name: Create JAR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build and Package with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: java-build
        path: target/FV*.jar

    # improves Dependabot alert quality
    - name: Update Dependency Graph
      uses: advanced-security/maven-dependency-submission-action@v4
